common: &default_settings
  environment: "sandbox"
  username: '<%= ENV['PAYPAL_API_USERNAME'] %>'
  password: '<%= ENV['PAYPAL_API_PASSWORD'] %>'
  signature: '<%= ENV['PAYPAL_API_SIGNATURE'] %>'
  application_id: '<%= ENV['PAYPAL_APPLICATION_ID'] %>'

development:
  <<: *default_settings

test:
  <<: *default_settings

production:
  <<: *default_settings
  environment: "sandbox"
